# Generated by Django 4.0.2 on 2023-09-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='frontwebsiteenquiry',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/frontwebsiteenquiry/'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='image',
            field=models.FileField(upload_to='media/general/offerbanner'),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.FileField(upload_to='media/package/'),
        ),
        migrations.AlterField(
            model_name='successstories',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/general/successstories'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/upload to/'),
        ),
    ]
