# Generated by Django 4.0.2 on 2023-09-29 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='word_doc',
            field=models.FileField(default=1, upload_to='media/package/worddoc/'),
            preserve_default=False,
        ),
    ]
