# Generated by Django 4.0.2 on 2023-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_package_word_doc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='lead_status',
            field=models.CharField(choices=[('New Lead', 'New Lead'), ('PreEnrolled', 'PreEnrolled'), ('Pending', 'Pending'), ('Accept', 'Accept'), ('Reject', 'Reject'), ('Archive', 'Archive'), ('Case Initiated', 'Case\xa0Initiated')], default='New Lead', max_length=100),
        ),
    ]
