# Generated by Django 4.2.5 on 2023-10-03 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0006_alter_assignroles_menu_name_alter_assignroles_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignroles',
            old_name='users',
            new_name='employee',
        ),
    ]
