# Generated by Django 4.2.5 on 2023-10-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0007_rename_users_assignroles_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Dashboard', 'Dashboard'), ('Enquiry', 'Enquiry'), ('Application Management', 'Application Management'), ('Employee Management', 'Employee Management'), ('Master Module', 'Master Module'), ('Add Questions', 'Add Questions'), ('Roles Management', 'Roles Management'), ('Edit Client', 'Edit Client'), ('Client Profile', 'Client Profile'), ('Profile', 'Profile'), ('View Employee', 'View Employee'), ('General', 'General'), ('Add Leads', 'Add Leads'), ('Agent Management', 'Agent Management'), ('Personal Detail', 'Personal Detail'), ('Commission Management', 'Commission Management'), ('Add Commission', 'Add Commission'), ('Commission', 'Commission'), ('Add Follow up', 'Add Follow up'), ('Follow ups', 'Follow ups'), ('Packages', 'Packages'), ('View Notification', 'View Notification'), ('Chatting', 'Chatting'), ('Chat', 'Chat'), ('Settings', 'Settings'), ('Add Appointment', 'Add Appointment'), ('View Appointment', 'View Appointment'), ('Update Case Status', 'Update Case Status'), ('Add Enquiry', 'Add Enquiry'), ('Report', 'Report'), ('Appointments', 'Appointments')], max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='assignroles',
            name='menu_name',
        ),
        migrations.AddField(
            model_name='assignroles',
            name='menu_name',
            field=models.ManyToManyField(to='crm_app.menu'),
        ),
    ]
