# Generated by Django 4.2.5 on 2023-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0008_menu_remove_assignroles_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignroles',
            name='employee',
            field=models.ManyToManyField(to='crm_app.employee'),
        ),
    ]
