# Generated by Django 4.0.2 on 2023-10-04 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0009_alter_assignroles_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignroles',
            name='employee',
            field=models.ManyToManyField(to='crm_app.Employee'),
        ),
        migrations.AlterField(
            model_name='assignroles',
            name='menu_name',
            field=models.ManyToManyField(to='crm_app.Menu'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='file',
            field=models.ImageField(upload_to='media/Employee/profile_pic/'),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=True)),
                ('last_updated_on', models.DateTimeField(auto_now=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm_app.branch'),
            preserve_default=False,
        ),
    ]
