# Generated by Django 4.2.5 on 2023-10-06 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0013_alter_employee_address_alter_employee_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='gender',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
