# Generated by Django 4.2.5 on 2023-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0014_agent_dob_agent_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='marital_status',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
