# Generated by Django 4.2.5 on 2023-10-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0015_agent_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='business_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
