# Generated by Django 4.2.5 on 2023-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0016_agent_business_type_agent_organization_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='account_holder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='account_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
