# Generated by Django 4.2.5 on 2023-10-06 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0017_agent_account_holder_agent_account_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_name', models.CharField(max_length=100)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.agent')),
                ('outsourceagent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.outsourcingagent')),
            ],
        ),
    ]
