# Generated by Django 4.2.5 on 2023-10-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0018_agentagreement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentagreement',
            name='agreement_file',
            field=models.FileField(blank=True, null=True, upload_to='media/Agreement/'),
        ),
    ]
