# Generated by Django 4.0.2 on 2023-10-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0020_document_document_size_alter_document_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visasubcategory',
            name='totalAmount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visasubcategory',
            name='cgst',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='visasubcategory',
            name='estimate_amt',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='visasubcategory',
            name='sgst',
            field=models.FloatField(),
        ),
    ]
