# Generated by Django 4.0.2 on 2023-10-07 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0022_outsourcingagent_account_holder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adhar_card_back',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='agent',
            name='adhar_card_front',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='agent',
            name='pancard',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='agent',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='outsourcingagent',
            name='adhar_card_back',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='outsourcingagent',
            name='adhar_card_front',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='outsourcingagent',
            name='pancard',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
        migrations.AddField(
            model_name='outsourcingagent',
            name='registration_certificate',
            field=models.FileField(blank=True, null=True, upload_to='media/Agent/Kyc'),
        ),
    ]
