# Generated by Django 4.2.5 on 2023-10-11 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0025_alter_casestatus_status_alter_currency_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='documentcategory',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='followup_status',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='followuppayment_status',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='followuptype',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/general/offerbanner'),
        ),
        migrations.AlterField(
            model_name='offerbanner',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/package/'),
        ),
        migrations.AlterField(
            model_name='package',
            name='word_doc',
            field=models.FileField(blank=True, null=True, upload_to='media/package/worddoc/'),
        ),
    ]
