# Generated by Django 4.2.5 on 2023-10-11 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0026_alter_casestatus_status_alter_currency_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='activeinactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/Agent/Profile Pic/'),
        ),
        migrations.AlterField(
            model_name='outsourcingagent',
            name='activeinactive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='outsourcingagent',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/OutSourcing/Agent/Profile Pic/'),
        ),
    ]
