# Generated by Django 4.0.2 on 2023-10-12 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0030_rename_user_visasubcategory_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visasubcategory',
            name='person',
        ),
        migrations.AddField(
            model_name='visasubcategory',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
