# Generated by Django 4.0.2 on 2023-10-12 09:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0031_remove_visasubcategory_person_visasubcategory_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visasubcategory',
            name='person',
        ),
        migrations.AddField(
            model_name='visasubcategory',
            name='person',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
