# Generated by Django 4.0.2 on 2023-10-13 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0032_remove_visasubcategory_person_visasubcategory_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='visa_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_category', to='crm_app.visacategory'),
        ),
        migrations.AlterField(
            model_name='package',
            name='visa_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_subcategory', to='crm_app.visacategory'),
        ),
    ]
