# Generated by Django 4.0.2 on 2023-10-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0033_alter_package_visa_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='word_doc',
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='media/package_images/')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.package')),
            ],
        ),
    ]
