# Generated by Django 4.0.2 on 2023-10-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0034_remove_package_image_remove_package_word_doc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Visa_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_category', to='crm_app.visacategory'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Visa_subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_subcategory', to='crm_app.visacategory'),
        ),
    ]
