# Generated by Django 4.0.2 on 2023-10-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0037_alter_casecategorydocument_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casecategorydocument',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_subcategory', to='crm_app.visacategory'),
        ),
    ]
