# Generated by Django 4.0.2 on 2023-10-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0040_employee_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_source',
            field=models.CharField(choices=[('COCO', 'Company Owned Company Operated'), ('COFO', 'Company Owned Franchise Operated'), ('FOCO', 'Franchise Owned Company Operated'), ('FOFO', 'Franchise Owned Franchise Operated')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
