# Generated by Django 4.0.2 on 2023-10-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0042_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
