# Generated by Django 4.2.5 on 2023-10-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0044_alter_enquiry_source_alter_enquiry_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='FirstName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='LastName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Salutation',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Miss', 'Miss'), ('Master', 'Master')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
