# Generated by Django 4.2.5 on 2023-10-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0045_alter_enquiry_dob_alter_enquiry_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
