# Generated by Django 4.2.5 on 2023-10-16 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0046_alter_enquiry_enquiry_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.package'),
        ),
    ]
