# Generated by Django 4.2.5 on 2023-10-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0047_alter_enquiry_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='activeinactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(choices=[('Application Management', 'Application Management'), ('Employee Management', 'Employee Management'), ('Agent Management', 'Agent Management'), ('Follow ups', 'Follow ups'), ('Products', 'Products'), ('FAQ', 'FAQ'), ('Appointments', 'Appointments')], max_length=255),
        ),
        migrations.AlterField(
            model_name='outsourcingagent',
            name='activeinactive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
