# Generated by Django 4.2.5 on 2023-10-18 10:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0048_alter_agent_activeinactive_alter_menu_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='passport_no',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
