# Generated by Django 4.2.5 on 2023-10-18 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0049_alter_enquiry_dob_alter_enquiry_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enquiry_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='passport_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
