# Generated by Django 4.2.5 on 2023-10-18 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0050_alter_enquiry_dob_alter_enquiry_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='Dob',
            field=models.DateField(default='2023-01-10'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Visa_country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.visacountry'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Visa_type',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Couple', 'Couple'), ('Family', 'Family')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='contact',
            field=models.CharField(default=54321, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='passport_no',
            field=models.CharField(default=5432, max_length=255),
            preserve_default=False,
        ),
    ]
