# Generated by Django 4.2.5 on 2023-11-01 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0053_remove_document_document_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquiry',
            old_name='phone',
            new_name='emergency_phone',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='digital_signature',
            field=models.FileField(blank=True, null=True, upload_to='media/Digital Signature/'),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mailing_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='mailing_phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Visa_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_category', to='crm_app.visacategory'),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='Visa_subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_subcategory', to='crm_app.visacategory'),
        ),
        migrations.CreateModel(
            name='Work_Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=244, null=True)),
                ('designation', models.CharField(blank=True, max_length=244, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=244, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('describe', models.TextField(blank=True, null=True)),
                ('enquiry_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.enquiry')),
            ],
        ),
    ]
