# Generated by Django 4.2.5 on 2023-11-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0054_rename_phone_enquiry_emergency_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='spouse_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='spouse_email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='spouse_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='spouse_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='spouse_passport',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
