# Generated by Django 4.2.5 on 2023-11-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0056_activitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('departure_city', models.CharField(max_length=100)),
                ('number_of_people', models.PositiveIntegerField()),
                ('departure_date', models.DateField()),
            ],
        ),
    ]
