# Generated by Django 4.2.5 on 2023-11-07 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0057_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='assign_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.employee'),
        ),
        migrations.AddField(
            model_name='outsourcingagent',
            name='assign_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.employee'),
        ),
    ]
