# Generated by Django 4.2.5 on 2023-11-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0060_alter_enquiry_firstname_alter_enquiry_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='advance_amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='amount',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='file_charges',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='package',
            name='package_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
