# Generated by Django 4.2.5 on 2023-11-28 13:01

import crm_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0061_alter_package_advance_amount_alter_package_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='chat_attachments/', validators=[crm_app.validators.validate_file_extension]),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='filename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
