# Generated by Django 4.2.5 on 2023-11-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0062_chatmessage_attachment_chatmessage_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact_no',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contact_no',
            field=models.CharField(default=1, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='outsourcingagent',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
