# Generated by Django 4.2.5 on 2023-12-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0063_alter_admin_contact_no_alter_agent_contact_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Sales', 'Sales'), ('dd', 'dd'), ('Presales/Assesment', 'Presales/Assesment')], max_length=100),
        ),
    ]
