# Generated by Django 4.2.5 on 2023-12-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0064_alter_department_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('Presales/Assesment', 'Presales/Assesment'), ('Sales', 'Sales'), ('Documentation', 'Documentation'), ('Visa Team', 'Visa Team'), ('HR', 'HR')], max_length=100),
        ),
    ]
